### ISSUE TITLE
NoClip not rendering correctly

### ISSUE THREAD

**Issue by Wxrlds** [JackyyTV/AvaritiaTweaks#11]
When in NoClip mode the rendering doesn't show most of the time. I would expect that the Armour NoClip renders the terrain like when in spectator mode but instead it just doesn't render the terrain most of the time. Depending on the angle which you are looking, more or less terrain gets rendered.

Spectator Mode:
![grafik](https://user-images.githubusercontent.com/42120270/104768650-4d4f6500-576e-11eb-8f94-c4bd35588a09.png)

Infinity Armour NoClip:
![grafik](https://user-images.githubusercontent.com/42120270/104768741-6f48e780-576e-11eb-830c-cc0c4830c91e.png)

(Ignore the yellow look of the caves, that's another mod messing with Night Vision)

**Comment by JackyyTV** [comment]
After much frustration, I've decided to just remove the no clip feature out of infinity armor completely starting with update 1.3.1, since that feature never functioned properly in the first place and I just simply don't have the time to maintain this mod anymore with my current job in real life.
