### ISSUE TITLE
Flight lock not getting removed

### ISSUE THREAD

**Issue by Wxrlds** [JackyyTV/AvaritiaTweaks#12]
When in NoClip with the Infinity Armour what happens is that your flight is locked so you don't fall through the world which is good. The problem starts when you are in NoClip and then remove your Armour when the flight is locked which causes you to stay in that flight locked state with no way to get rid of the fly lock besides equiping the Armour again and disabling NoClip.

**Comment by JackyyTV** [comment]
No clip mode is being removed, see #11 for explanation.
