### ISSUE TITLE
NoClip not working on Multiplayer

### ISSUE THREAD

**Issue by Wxrlds** [JackyyTV/AvaritiaTweaks#13]
Title says it all, in multiplayer the NoClip mode doesn't work. Everything works fine in Singleplayer.
This also happens with only Avarita + Tweaks installed.

Using:
Forge 14.23.5.2847
Avaritia-1.12.2-3.3.0.37-universal.jar
AvaritiaTweaks-1.12.2-1.3.jar
CodeChickenLib-1.12.2-3.2.3.358-universal.jar
GunpowderLib-1.12.2-1.1.jar
jei_1.12.2-4.16.1.302.jar

**Comment by YouSeeMeRunning2** [comment]
I can confirm that this is also an issue for the server I play on. I have full infinity gear with the enhancement crystals and using version AvaritiaTweaks-1.12.2-1.3.jar

**Comment by JackyyTV** [comment]
No clip mode is being removed, see #11 for explanation.
