### ISSUE TITLE
config disable/enable night vision on helmet

### ISSUE THREAD

**Issue by Nearsky22** [JackyyTV/AvaritiaTweaks#14]
I don't really like night vision it makes my shaders look too bright

**Comment by JackyyTV** [comment]
You can already remove the night vision effect yourself in the config, just remove the line `minecraft:night_vision` from the following entry in the config file:
```
# Put a list of Potion registery names you would like to have when wearing Infinity Helmet
# Requires Enhancement Crystal to be installed on Infinity Helmet
S:infinityHelmetPotionEffects <
    minecraft:night_vision
>
```

**Comment by Nearsky22** [comment]
I've tried it but it doesn't work

Pada tanggal Kam, 20 Mei 2021 pukul 05.54 Jacky ***@***.***>
menulis:
