### ISSUE TITLE
Game crashes when opening Controls GUI

### ISSUE THREAD

**Issue by ephys** [JackyyTV/AvaritiaTweaks#2]
I'm getting a weird crash that is really hard to track down. It doesn't mention this mod specifically but only occur when this mod is loaded.

Here is the crash report: https://gist.github.com/Ephys/597a64c9b14761a6c67b0a9996c3c51e

I think it may be related to https://github.com/strikerrocker/VanillaTweaks/issues/19 -- I had the exact same issue with that mod alone too.

**Comment by JackyyTV** [comment]
That's very strange. Does that happen every time or just at occasions?

**Comment by ephys** [comment]
Happened every time as soon as the GUI was opened 

Edit: This might be interesting, I disabled `infinityArmorNoClip` in the config. I'll try with it on

**Comment by ephys** [comment]
Definitely interesting, the crash only happens if `infinityArmorNoClip` is false. Maybe creating the keybind but not registering it is the source of the crash?

**Comment by JackyyTV** [comment]
Might be something to do with the keybind, I think I should always register the keybind but only disable No Clip mode for ingame.

**Comment by ephys** [comment]
Or only instanciate the KeyBind if it's going to be registered. It doesn't look like it's being referenced from anywhere in the code so it shouldn't be an issue

**Comment by JackyyTV** [comment]
I am actually.
https://github.com/JackyyTV/AvaritiaTweaks/blob/8e8a87396abfa411c661bcaea418a88930b07b9d/src/main/java/jackyy/avaritiatweaks/tweaks/ModEventsHandler.java#L157-L162
But it's fine, that can be fixed quite easily.

**Comment by JackyyTV** [comment]
New version coming out in a few hours, hopefully should fix your problems.
![image](https://user-images.githubusercontent.com/11830494/35779451-26054f98-0a08-11e8-914f-fd210484cf2d.png)

**Comment by ephys** [comment]
Thank youu!
