### ISSUE TITLE
Game crashes if botania isn't present

### ISSUE THREAD

**Issue by ephys** [JackyyTV/AvaritiaTweaks#3]
Hello!

[These](https://github.com/JackyyTV/AvaritiaTweaks/blob/2763f7267f57d94cc52a9520d6ed1a0413eb6f20/src/main/java/jackyy/avaritiatweaks/AvaritiaTweaks.java#L23) [lines](https://github.com/JackyyTV/AvaritiaTweaks/blob/2763f7267f57d94cc52a9520d6ed1a0413eb6f20/src/main/java/jackyy/avaritiatweaks/tweaks/ModTweaks.java#L63) lead me to believe that boania is an optional dependency

but ModTweaks runs botania related code even if the mod isn't present: https://github.com/JackyyTV/AvaritiaTweaks/blob/2763f7267f57d94cc52a9520d6ed1a0413eb6f20/src/main/java/jackyy/avaritiatweaks/tweaks/ModTweaks.java#L29

Leading to this crash report: https://gist.github.com/Ephys/7d647142970b6845076cf939367fe994

**Comment by JackyyTV** [comment]
I do have some checks for if Botania is loaded or not, perhaps it's not checking it very well. Will have a look later.
