### ISSUE TITLE
NoClip feature breaks Spectator Mode

### ISSUE THREAD

**Issue by brisingraerowing** [JackyyTV/AvaritiaTweaks#4]
With this mod installed, players in Spectator Mode cannot go through blocks. Likely related to the Infinity Armor NoClip feature.

**Comment by Morpheus1101** [comment]
Does this occur with just Avaritia installed?

**Comment by brisingraerowing** [comment]
With just Avaritia, Spectator works perfectly fine. Only when I add this mod does it break.

**Comment by JackyyTV** [comment]
I know exactly what's wrong, will push a fix in the next few days (along with new features).

**Comment by Enilo** [comment]
This issue is still in the released version of the mod on CurseForge and you seem to have a fix. Care to publish it?

**Comment by JackyyTV** [comment]
I have a job now, so don't really have time to manage MC modding stuff anymore, but I'll try and push an update soon.

**Comment by Enilo** [comment]
Take your time, just thought I would put in a reminder since it seemed to have been forgotten and I just encountered the bug.
