### ISSUE TITLE
Enhancement Crystal Recipe Issue

### ISSUE THREAD

**Issue by Cazadorsniper** [JackyyTV/AvaritiaTweaks#7]
I can't seem to get the enhancement crystals recipe to show up in Extended Crafting's 9x9 table, all I'm doing is moving the same recipe from avaritia dire crafting table to extended crafting table.

https://pastebin.com/SPGrw4M1

**Comment by JackyyTV** [comment]
Have you tried not using OreDict in the recipe? It might be a bug with Extending Crafting since my mod has absolutely no interactions with it.

**Comment by Cazadorsniper** [comment]
I can try and see although, other avaritia recipes had no problem switching over while using oredict

**Comment by Cazadorsniper** [comment]
Didn't work, I even turned one of the diamonds for the infinitato to its oredict and the infinitato still works as intended. Its only the enhancement crystal's recipe that shows up blank. https://gyazo.com/0362461983530f8bbbdcb1f69b0eda29

**Comment by JackyyTV** [comment]
That's very weird, I'll have to further investigate that.

**Comment by BlakeBr0** [comment]
@Cazadorsniper first line seems to have 10 items

**Comment by JackyyTV** [comment]
Well then, so it's not a bug...
